name: Kickass Compassion
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51218
title: 'Kickass Compassion '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee8c6'
    - '#a1cbbd'
    - '#9fa88c'
    - '#9a853c'
    - '#238b72'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
