name: Kickass Compassion
favicon: null
layout_spectrum: 0.48752
typography_spectrum: 0.51218
title: 'Kickass Compassion '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2d4e'
    - '#000000'
    - '#6e5958'
    - '#93adde'
    - '#edd6ce'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
