name: Kickass Compassion
favicon: null
layout_spectrum: 0.70692
typography_spectrum: 0.4162
title: 'Kickass Compassion. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2d4e'
    - '#000000'
    - '#6e5958'
    - '#93adde'
    - '#edd6ce'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
